openapi: "3.0.3"
info:
  version: 1.0.0
  title: Alien
  license:
    name: MIT
servers:
  - url: http://localhost:3000
paths:
  /nextState:
    get:
      summary: nextState
      operationId: nextState
      tags:
        - nextState
      parameters:
        - name: command
          in: query
          description: command
          required: true
          schema:
            type: string
        - name: payload
          in: query
          description: command
          required: false
          schema:
            type: string
      responses:
        '200':
          description: nextState
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NextState"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Direction:
      type: string
      enum: [left, right]
      x-enumNames: [HIGH, MEDIUM, LOW]

    Option:
      type: object
      required:
        - value
      properties:
        value:
          type: string
        id:
          type: integer

    CommandDescription:
      type: object
      required:
        - name
        - needPayload
      properties:
        name:
          type: string
        needPayload:
          type: boolean

    Question:
      type: object
      required:
        - text
      properties:
        text:
          type: string
        options:
          type: array
          maxItems: 100
          items:
            $ref: "#/components/schemas/Option"

    StateMachineResponse:
      type: object
      required:
        - message
        - renderComponentName
      properties:
        message:
          type: string
        error:
          type: string
        renderComponentName:
          type: string
        nextCommands:
          type: array
          items:
            $ref: "#/components/schemas/CommandDescription"
        question:
          type: object
          $ref: "#/components/schemas/Question"

    NextState:
      type: object
      required:
        - stateMachineResponse
      properties:
        stateMachineResponse:
          type: object
          $ref: "#/components/schemas/StateMachineResponse"

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
