openapi: "3.0.3"
info:
  version: 1.0.0
  title: Swagger Greeting
  license:
    name: MIT
servers:
  - url: http://localhost:3000
paths:
  /greetings:
    get:
      summary: sayHello
      operationId: sayHello
      tags:
        - greetings
      responses:
        '200':
          description: sayingHello
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Greeting"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Greeting:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    Greetings:
      type: array
      maxItems: 100
      items:
        $ref: "#/components/schemas/Greeting"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
